# Generated by Django 4.2 on 2023-05-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_car_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='car_id',
        ),
        migrations.AddField(
            model_name='contact',
            name='car_slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
