# Generated by Django 4.2 on 2023-05-07 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_car_options'),
        ('contacts', '0003_remove_contact_car_id_contact_car_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_contact', to='cars.car'),
        ),
    ]
