# Generated by Django 4.2 on 2023-05-07 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contact_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='car',
        ),
    ]
