# Generated by Django 4.2 on 2023-05-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_remove_contact_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='car_price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
