# Generated by Django 4.0.6 on 2023-05-10 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=150)),
                ('subject', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='photo/%Y/%m/%d/')),
                ('facebook_link', models.URLField(max_length=120)),
                ('twitter_link', models.URLField(max_length=120)),
                ('google_plus_link', models.URLField(max_length=120)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
